main: com.elemengine.elemengine.Elemengine
name: Elemengine
version: 1.0.0
description: Elemental bending implemented into Minecraft Spigot
api-version: "1.20"
authors: [Simplicitee]
commands:
  elemengine:
    aliases: [e, bending, b]
    